REM VGER_REPORT CMP_FSEMAIL

  DROP TABLE "VGER_REPORT"."CMP_FSEMAIL" ;
  
  CREATE TABLE "VGER_REPORT"."CMP_FSEMAIL" 
   (	"UNIVERSITYID" VARCHAR2(9 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(35 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"DEPTCODE" VARCHAR2(4 BYTE), 
	"DEPARTMENT" VARCHAR2(30 BYTE), 
	 CONSTRAINT "CMP_FSEMAIL_PK" PRIMARY KEY ("UNIVERSITYID") ENABLE
   ) ;
 
REM VGER_REPORT CMP_FSEMAIL_PK

  CREATE UNIQUE INDEX "VGER_REPORT"."CMP_FSEMAIL_PK" ON "VGER_REPORT"."CMP_FSEMAIL" ("UNIVERSITYID") 
  ;
 
