
REM VGER_REPORT PATRON_SIF

  CREATE TABLE "VGER_REPORT"."PATRON_SIF" 
   (	"SIF_ID" NUMBER NOT NULL ENABLE, 
	"SIF_RECORD" VARCHAR2(2000), 
	"PROCESSED" NUMBER DEFAULT 0
   ) ;
 CREATE UNIQUE INDEX "VGER_REPORT"."PATRON_SIF_PK" ON "VGER_REPORT"."PATRON_SIF" ("SIF_ID") 
  ;
  ALTER TABLE "VGER_REPORT"."PATRON_SIF" ADD CONSTRAINT "PATRON_SIF_PK" PRIMARY KEY ("SIF_ID") ENABLE;
 