
REM VGER_SUPPORT PATRON_GROUP_COMPONENTS

  CREATE TABLE "VGER_SUPPORT"."PATRON_GROUP_COMPONENTS" 
   (	"PATRON_GROUP_ID" NUMBER NOT NULL ENABLE, 
	"TYPE" NUMBER, 
	"HIERARCHY" NUMBER, 
	"CHANGEABLE" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"SCHOOL" NUMBER
   ) ;
 CREATE UNIQUE INDEX "VGER_SUPPORT"."PATRON_GROUP_COMPONENTS_PK" ON "VGER_SUPPORT"."PATRON_GROUP_COMPONENTS" ("PATRON_GROUP_ID") 
  ;
  ALTER TABLE "VGER_SUPPORT"."PATRON_GROUP_COMPONENTS" ADD CONSTRAINT "PATRON_GROUP_COMPONENTS_PK" PRIMARY KEY ("PATRON_GROUP_ID") ENABLE;
  ALTER TABLE "VGER_SUPPORT"."PATRON_GROUP_COMPONENTS" ADD CONSTRAINT "PATRON_GROUP_COMPONENTS_CH" CHECK (
changeable in ('Y', 'N')
) ENABLE;
 